name: macOS build and test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15-intel, macos-latest]  # macos-15-intel = x86_64, macos-latest = ARM64
        include:
          - os: macos-15-intel
            arch: x86_64
            abi: darwin_x86_64
          - os: macos-latest
            arch: arm64
            abi: darwin_arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show system info
      run: |
        uname -a
        uname -m
        cc --version
    
    - name: Build library
      run: make all
    
    - name: Run tests
      run: make test
    
    - name: Show ABI name
      run: make abiname
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.abi }}
        path: lib/${{ matrix.abi }}/libstackman.a
